version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: menumaster_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - menumaster_mongo_data:/data/db

  web:
    build: .
    container_name: menumaster_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  mongo-express:
    image: mongo-express
    container_name: menumaster_mongo_ui
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@db:27017/
    depends_on:
      - db

volumes:
  menumaster_mongo_data: